//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Installer.Properties.Resources.zh", typeof(Resources_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建开始菜单快捷方式.
        /// </summary>
        public static string CreateStartMenuShortcut {
            get {
                return ResourceManager.GetString("CreateStartMenuShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string dcsPathButton {
            get {
                return ResourceManager.GetString("dcsPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装 / 更新 DCS-SRS.
        /// </summary>
        public static string InstallButton {
            get {
                return ResourceManager.GetString("InstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在安装....
        /// </summary>
        public static string InstallingButton {
            get {
                return ResourceManager.GetString("InstallingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装DCS客户端脚本 - 只有SRS客户端需要，仅开服不需要.
        /// </summary>
        public static string InstallScriptsCheckbox {
            get {
                return ResourceManager.GetString("InstallScriptsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简单无线电独立版 (SRS) 安装程序 -.
        /// </summary>
        public static string intro {
            get {
                return ResourceManager.GetString("intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更改安装设置？.
        /// </summary>
        public static string MsgBoxChange {
            get {
                return ResourceManager.GetString("MsgBoxChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你想要更改设置吗？
        ///
        ///是 - 暂停安装以进行修改
        ///
        ///否 - 以先前的安装路径和脚本作为默认
        ///
        ///如果不确定，猛击“是”！.
        /// </summary>
        public static string MsgBoxChangeText {
            get {
                return ResourceManager.GetString("MsgBoxChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先退出DCS.
        /// </summary>
        public static string MsgBoxDCS {
            get {
                return ResourceManager.GetString("MsgBoxDCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装或卸载只有在DCS关闭时才能进行！
        ///
        ///退出DCS后重试.
        /// </summary>
        public static string MsgBoxDCSText {
            get {
                return ResourceManager.GetString("MsgBoxDCSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先解压.
        /// </summary>
        public static string MsgBoxExtracted {
            get {
                return ResourceManager.GetString("MsgBoxExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有解压.
        /// </summary>
        public static string MsgBoxExtracted2 {
            get {
                return ResourceManager.GetString("MsgBoxExtracted2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请解压整个安装压缩包至一个文件夹，再从文件夹内运行Installer。
        ///
        ///不要在压缩包里运行Installer，跑 不 起 来！.
        /// </summary>
        public static string MsgBoxExtractedText {
            get {
                return ResourceManager.GetString("MsgBoxExtractedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到安装所需文件，无法安装。
        ///
        ///在运行Installer之前，请确保你解压了整个压缩包。.
        /// </summary>
        public static string MsgBoxExtractedText2 {
            get {
                return ResourceManager.GetString("MsgBoxExtractedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRS安装程序.
        /// </summary>
        public static string MsgBoxFolder {
            get {
                return ResourceManager.GetString("MsgBoxFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在保存的游戏中找不到DCS文件夹！
        ///
        ///请确认你的“保存的游戏 (Saved Games)”路径正确
        ///
        ///你要选择的是”保存的游戏“文件夹本身，不是里面的DCS文件夹，也不是DCS的安装位置。.
        /// </summary>
        public static string MsgBoxFolderText {
            get {
                return ResourceManager.GetString("MsgBoxFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装程序错误.
        /// </summary>
        public static string MsgBoxInstallError {
            get {
                return ResourceManager.GetString("MsgBoxInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装出错，请把你的”installer-log.txt“文件发到SRS的Discord频道以获取帮助.
        /// </summary>
        public static string MsgBoxInstallErrorText {
            get {
                return ResourceManager.GetString("MsgBoxInstallErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装 / 更新成功完成！
        ///DCS脚本已安装至:
        ///.
        /// </summary>
        public static string MsgBoxInstallSuccessText {
            get {
                return ResourceManager.GetString("MsgBoxInstallSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安装 / 更新成功完成！.
        /// </summary>
        public static string MsgBoxInstallSuccessText2 {
            get {
                return ResourceManager.GetString("MsgBoxInstallSuccessText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRS安装程序.
        /// </summary>
        public static string MsgBoxInstallTitle {
            get {
                return ResourceManager.GetString("MsgBoxInstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRS成功卸载！
        ///
        ///器文件夹内的配置文件已保留，方便日后取用。.
        /// </summary>
        public static string MsgBoxRemovedText {
            get {
                return ResourceManager.GetString("MsgBoxRemovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRS成功卸载！.
        /// </summary>
        public static string MsgBoxRemovedText2 {
            get {
                return ResourceManager.GetString("MsgBoxRemovedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卸载程序错误.
        /// </summary>
        public static string MsgBoxUninstallError {
            get {
                return ResourceManager.GetString("MsgBoxUninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卸载出错，请把你的”installer-log.txt“文件发到SRS的Discord频道以获取帮助.
        /// </summary>
        public static string MsgBoxUninstallErrorText {
            get {
                return ResourceManager.GetString("MsgBoxUninstallErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在卸载SRS.
        /// </summary>
        public static string MsgBoxUninstalling {
            get {
                return ResourceManager.GetString("MsgBoxUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卸载 DCS-SRS.
        /// </summary>
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请注意: 服务器使用需手动安装 DCS-SRS-AutoConnectGameGUI.lua。
        ///此文件可在SRS安装目录中的Scripts文件夹内找到，内含安装说明。.
        /// </summary>
        public static string ServerNote {
            get {
                return ResourceManager.GetString("ServerNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览.
        /// </summary>
        public static string srPathButton {
            get {
                return ResourceManager.GetString("srPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一步: 选择SRS安装位置.
        /// </summary>
        public static string step2 {
            get {
                return ResourceManager.GetString("step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第二步: 找到“保存的游戏”文件夹 - 非DCS.
        /// </summary>
        public static string step3 {
            get {
                return ResourceManager.GetString("step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第三步: 安装或卸载 DCS-SRS.
        /// </summary>
        public static string step4 {
            get {
                return ResourceManager.GetString("step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCS-SRS 安装程序.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
